CREATE DATABASE IF NOT EXISTS company;

USE company;

CREATE TABLE IF NOT EXISTS entries
(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
RecordNumber VARCHAR(64),
CustomerName VARCHAR(64),
Email VARCHAR(64),
Phone VARCHAR(64),
Stat INT(1) DEFAULT 0,
RAWS3URL VARCHAR(200),
FINSIHEDS3URL VARCHAR(200)
);
